name: shuttlecock
description: An algegraic types library inspired by the course Category theory for programmers by Bartosz Milewski. https://www.youtube.com/playlist?list=PLbgaMIhjbmEnaH_LTkxLI7FMa2HsnawM_
version: 0.0.1
author: Alexei Eleusis Díaz Vera <alexei.eleusis@gmail.com>
homepage: https://github.com/alexeieleusis/shuttlecock

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  lib_name: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
