name: shuttlecock
description: An algebraic types library inspired by the course Category theory for programmers by Bartosz Milewski. https://www.youtube.com/playlist?list=PLbgaMIhjbmEnaH_LTkxLI7FMa2HsnawM_
version: 0.4.1
author: Alexei Eleusis Díaz Vera <alexei.eleusis@gmail.com>
homepage: https://github.com/alexeieleusis/shuttlecock

environment:
  sdk: '>=1.22.1'

dependencies:
  meta: ^1.1.0
  tuple: ^1.0.1

dev_dependencies:
  test: '>=0.12.24+6 <0.13.0'
